In [ ]:
import tensorflow as tf
print(('Your Tensor Flow Version: {0}').format(tf.__version__))

Your Tensor Flow Version: 2.11.0


In [ ]:
#Create a constant tensor A
A = tf.constant([[4,3],
                 [6,1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]], dtype=int32)>

In [ ]:
#Create a constant tensor V
V = tf.constant([[3,1],
                 [5,2]])
V
B = tf.constant([[7,8],
                 [4,5]])
B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [4, 5]], dtype=int32)>

In [ ]:
#Concatenate columns
AB_concatenated = tf.concat(values=[A,B],axis=1)
AB_concatenated

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 7, 8],
       [6, 1, 4, 5]], dtype=int32)>

In [ ]:
#Concatenate rows
AB_concatenated = tf.concat(values=[A,B],axis=0)
AB_concatenated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [7, 8],
       [4, 5]], dtype=int32)>

In [ ]:
tensor = tf.zeros(shape=[3,4],dtype=tf.int32)
tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [ ]:
tensor1 = tf.ones(shape=[3,4],dtype=tf.int32)
tensor1

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [ ]:
reshaped_tensor = tf.reshape(tensor=tensor,shape=[4,3])
reshaped_tensor

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [ ]:
#uniform
uniform_tensor = tf.random.uniform(shape=[4,3],dtype=tf.float32)
uniform_tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.32470763, 0.3116157 , 0.05165792],
       [0.41537082, 0.7554729 , 0.09230936],
       [0.40398657, 0.03941035, 0.4686823 ],
       [0.37952638, 0.441949  , 0.16438723]], dtype=float32)>

In [ ]:
#Typecast a tensor
tensor = tf.constant([[4.6,4.2],
                       [7.5,3.6],
                       [2.7,9.4],
                       [2.7,9.4]],
                     dtype=tf.float32)
tensor_as_int = tf.cast(tensor,tf.int32)
print(tensor_as_int)

tf.Tensor(
[[4 4]
 [7 3]
 [2 9]
 [2 9]], shape=(4, 2), dtype=int32)


In [ ]:
 a_tran = tf.transpose(tensor_as_int)
 a_tran

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 7, 2, 2],
       [4, 3, 9, 9]], dtype=int32)>

In [ ]:
#Matrix multiplication of tensors
D = tf.constant([[5,8],[3,9]])

#some vector v
v = tf.constant([[4],
                 [2]])
Dv = tf.matmul(D,v)
Dv

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[36],
       [30]], dtype=int32)>

In [ ]:
#Creating an identity matrix
A = tf.constant([
    [4,9],
    [5,6],
    [1,8]
])
rows,columns = A.shape
print("rows: ",rows,"columns: ",columns)

#Making an identity matrix
A_identity = tf.eye(num_rows = rows,
                    num_columns = columns,
                    dtype = tf.int32)
A_identity

rows:  3 columns:  2


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1],
       [0, 0]], dtype=int32)>